### ISSUE TITLE
Add r-spatial.org to R-bloggers

### ISSUE THREAD

**Issue by nuest** [edzer/r-spatial#14]
I noticed r-spatial.org is not on the list of R-bloggers blogs: https://www.r-bloggers.com/blogs-list/

The onboarding is quite simple. I'd say we can just use the regular RSS feed because all posts are related to R. I would be happy to do this if welcome., i.e. if the contributors are happy to have the content appear on the R-bloggers site.

- [x] submit at https://www.r-bloggers.com/add-your-blog/
- [x] add R-bloggers to blogroll (already the case)

**Comment by tim-salabim** [comment]
Great Idea!

**Comment by nuest** [comment]
@edzer Fine by you?

**Comment by edzer** [comment]
Sure, go ahead!

**Comment by nuest** [comment]
Submitted, will close the issue once r-spatial is listed.

![image](https://user-images.githubusercontent.com/1325054/29874369-d2bdb778-8d96-11e7-9e3d-5e0f0ff1fef2.png)

**Comment by pat-s** [comment]
@nuest any update here? I think I already asked @edzer about one year ago about this and back then I mailed Tal several times and got no reply.

**Comment by nuest** [comment]
No update on my end.

@talgalili Can you give us an update on the request to include `r-spatial.org` to R-Bloggers?

**Comment by nuest** [comment]
Well, sometimes things just take longer. I got an email today with issues that needed to be fixed:

- [x] reference to R bloggers not found, will point to https://www.r-spatial.org/blogroll/
- [x] full text in feed missing - fixed in #32
  - [x] recommended to check with https://simplepie.org/demo/?feed=https%3A%2F%2Fwww.r-spatial.org%2Ffeed.xml - will do after merge
- [x] reply to email

**Comment by talgalili** [comment]
If you are using Hugo/blogdown, you may take a look at the following
two urls:
    - https://randomgeekery.org/2017/09/15/full-content-hugo-feeds/
    -
https://coolbutuseless.bitbucket.io/2018/02/07/blogdown-rss-feed-of-full-articles/

**Comment by nuest** [comment]
@talgalili I just replied to your mail and hope everything is in order now.

**Comment by nuest** [comment]
**Done**

![image](https://user-images.githubusercontent.com/1325054/47288217-74517780-d5f5-11e8-8cc7-9c0c6540f7cb.png)



I also received the following infos, none of which should be an issue for r-spatial.org, but I'll put them here fore future reference:

> Lastly, a few reminders (these are important to make sure your feed will stay on r-bloggers in the future). PLEASE READ THEM CAREFULLY: 
> 1) The feed you submitted should ONLY be about R.  If at any point you start writing about other things in your blog, please make sure to email me ASAP of an R-bloggers specific feed to stay update with.
> 2) Your feed should NOT include tweet like articles (e.g: Short pieces of text, or ones that are mainly about trivial links to something).
> 3) The feed should include “well written” articles: please make sure to proof read your English and avoid foul language (once a post gets on the site, it is harder to update/fix it - so please try to get it right the first time)
> 4) Make sure your feed has its full content released (not abstract/excerpts).
> 5) Please avoid overloading/spamming the site with: “too many” posts per day, ads in the posts (banners, affiliate links etc.). Such content may be changed by R-bloggers (automatically or manually) or removed. If you wish to make sure your blogging practices fits the site you can e-mail me for questions.
> 6) Make sure the RSS/HTML of your content is well formatted - otherwise it would not be able to load on r-bloggers.  This includes NOT copy-pasting from RStudio's notebook extension.
> You can always verify the validity of your RSS feed using the following two urls:
> https://validator.w3.org/feed/
> https://simplepie.org/demo/
> 7) Copyrights - make sure you have explicit copyrights for using any type of material you have on your blog (Text, images, code) and to share it forward. You have the full responsibility for the material you share, so be careful with it.
