### ISSUE TITLE
Local regression spgwr error

### ISSUE THREAD

**Issue by jebyrnes** [edzer/r-spatial#19]
On http://rspatial.org/analysis/rst/6-local_regression.html

```
library( spgwr )
## Error in library(spgwr): there is no package called 'spgwr'
bw <- gwr.sel(pan ~ ALT, data=spt)
## Error in eval(expr, envir, enclos): could not find function "gwr.sel"
bw
## Error in eval(expr, envir, enclos): object 'bw' not found
```

and everything thereafter is an error.

**Comment by tim-salabim** [comment]
Sorry for the confusion here, but the blog you refer to has nothing to do with this repository. There is a subtle difference in the naming. r-spatial.org (this repository) vs rspatial.org (mind the missing hyphen "-" in the name). Hence, there is nothing we can do about this. You might want to alert the authors of rspatial.org though.
