### ISSUE TITLE
Update stars blog post

### ISSUE THREAD

**Issue by jeroen** [edzer/r-spatial#25]
The example from the [stars post](https://www.r-spatial.org/r/2017/11/23/stars1.html) which is referenced in the readme no longer works :( Has `st_stars` been renamed to `read_stars`?

**Comment by edzer** [comment]
yes,
```r
vignette("blog1")
```
does it (although I see it not installed when using `devtools::install_github`). Will add to the blog & README.md.

**Comment by edzer** [comment]
Updated now.

**Comment by jeroen** [comment]
Ok. Why not just fix the code itself on the website? That's where most new users will start.
