### ISSUE TITLE
view raw Rmd seems to be a broken link

### ISSUE THREAD

**Issue by andysouth** [edzer/r-spatial#34]
When I click on View raw Rmd it takes me here that gives me a 404 error

https://raw.githubusercontent.com//r-spatial/r-spatial.org/gh-pages/_rmd/2018-10-02-ggplot2-sf.Rmd

Removing the extra / seems to fix it.

https://raw.githubusercontent.com/r-spatial/r-spatial.org/gh-pages/_rmd/2018-10-02-ggplot2-sf.Rmd

**Comment by edzer** [comment]
Thanks, @AndySouth - should work now.
