### ISSUE TITLE
Date of RSAGA blog post got updated accidentally

### ISSUE THREAD

**Issue by pat-s** [edzer/r-spatial#35]
From March to October: https://www.r-spatial.org/r/2018/10/20/rsaga-1.0.0

However, I do not see any change in the corresponding files or the commit history.

Probably happened when the "Drawing beautiful maps programmatically with R, sf and ggplot2" posts were added.

Nothing problematic and it probably takes too much time to debug this for now.
Just wanted to let you know. Feel free to close the issue after reading.

**Comment by edzer** [comment]
Your point is: the date in the url and on the blog are false, right?

**Comment by pat-s** [comment]
Yes, the actual post date was: March, 20th
Now the post was re-published on October, 20th

**Comment by edzer** [comment]
Odd! Given the date, it may have to do with getting the r-bloggers stuff working, #14

**Comment by pat-s** [comment]
Now the RSAGA post is completely gone from the list. It is still within `_posts` though.

**Comment by pat-s** [comment]
@edzer The RSAGA post was again republished and somehow even picked up by the r-weekly team.

Any idea how we can prevent this in the future and why it happened in the first place?

The commit history does not indicate any related event and I do not see any different setting in the RSAGA blog post?
