### ISSUE TITLE
How to I correct a type on http://rspatial.org/spatial?

### ISSUE THREAD

**Issue by riazarbi** [edzer/r-spatial#36]
Usually there's a link to the github source, and I can submit a pull request.

**Comment by edzer** [comment]
Maybe here: https://github.com/rspatial/rspatial-web

Note that there is an r-spatial.org and an rspatial.org. @rhijmans this is not the first time that this confuses users; have you ever given it a thought to merge both efforts?

**Comment by riazarbi** [comment]
Yep, it got me. Thanks for the friendly redirection.
