### ISSUE TITLE
How to get the air quality dataset in Chapter 16 Interpolation and Geostatistics

### ISSUE THREAD

**Issue by xiaochi-liu** [edzer/r-spatial#52]
Hello. I'm reading the book _Spatial Data Science_. It's awesome! I like doing spatial staff in the sf way~

In chapter 16, although the URL of air quality data is provided, and it is said:

> It returns a text file with a set of URLs to CSV files, each containing the hourly values for the whole period for a single measurement station. These files were downloaded and converted to the right encoding using the dos2unix command line utility.

I'm still confused about how to get the data in the right place so that I can follow the chapter.  Could you please provide more details?

Many thanks for your help!

**Comment by edzer** [comment]
Answered here: https://github.com/edzer/sdsr/issues/40
