### ISSUE TITLE
Homepage set to wrong URL ?

### ISSUE THREAD

**Issue by jeroen** [edzer/r-spatial#54]
The `homepage` of the `r-spatial` github organization is set to another organization, `https://github.com/rspatial`. I am not sure if this is intended, but this property is also used to get the official homepage of the  "r-spatial" organization by other front-ends, for example https://r-spatial.r-universe.dev/ which is pretty confusing.

<img width="615" alt="Screen Shot 2021-01-11 at 2 33 11 AM" src="https://user-images.githubusercontent.com/216319/104141120-61cddf00-53b5-11eb-8920-6fed771339dc.png">

**Comment by tim-salabim** [comment]
Thanks, I've fixed the link.
