### ISSUE TITLE
Can’t connect to the server at r-spatial.org

### ISSUE THREAD

**Issue by samuel-rosa** [edzer/r-spatial#70]
It seems that the r-spatial.org is out. I have tried using my home Wi-Fi network and mobile data. None worked.

![image](https://github.com/user-attachments/assets/6c299bc5-d600-4f1a-8a70-72784f002ece)

**Comment by tim-salabim** [comment]
I can confirm. @edzer where is this site hosted?

**Comment by edzer** [comment]
Thx, fixed!
